# Array
array() is a NumPy function used to convert Python lists or tuples into NumPy arrays, which can then be used for fast numerical operations.

## Main points
All elements must be the same datatype.

Can create 1D, 2D, or higher-dimensional arrays.

Supports mathematical operations on the whole array (vectorized operations).

Arrays created are of type numpy.ndarray.

Once a list/tuple becomes a NumPy array, it is faster and more memory-efficient than a Python list.



## 1D Array (One-Dimensional Array)

A 1D array is a single row of elements.

It is basically a vector and has only one axis (dimension).



In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

print(arr1)

[1 2 3 4 5]


1️⃣ import numpy as np

This imports the NumPy library so you can use all its functions.

as np → gives NumPy a short name (np) to type less.

Without this line, np.array() will not work.

2️⃣ arr1 = np.array([1,2,3,4,5])

np.array() → creates a NumPy array from a Python list [1,2,3,4,5].

arr1 → variable name where the array is stored.

3️⃣ print(arr1)

Prints the contents of the array.

## 2D Array (Two-Dimensional Array)

A 2D array is like a table or grid.

It has rows and columns.

Each row can have multiple elements.

Looks like a matrix or table

Can access elements by row and column

Can store numbers for calculations

In [2]:
# import numpy as np

arr2d = np.array([[1,3,2],
                  [6,5,3]])

print(arr2d)

[[1 3 2]
 [6 5 3]]


## 3D Array (Three-Dimensional Array)

A 3D array is like a stack of 2D arrays.

Think of it as multiple tables stacked on top of each other.

Each “layer” is a 2D array.

Consists of multiple 2D arrays stacked together

Can store more complex data (like images and videos)

Each element is still a number

In [3]:
# import numpy as np

arr3d = np.array([[[1,2],
                  [4,5]],
                  
                  [[6,7],
                  [8,9]]])


print(arr3d)

[[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]


## 0D Array (Zero-Dimensional Array)

A 0D array is a single value stored as a NumPy array.

It contains only one element.

It has no rows and no columns.

So it is just one number, but stored as a NumPy array.

### Main Points

Contains only one value

Has no dimensions

Created when we pass a single number to the array function

In [4]:

arr0d = np.array(10)

print(arr0d)

10


## Placeholder

Placehplder create arrays which is already filled with a specific value.

### 1️⃣np.zeros()

np.zeros() creates an array filled with zeros (0).

It is useful when you want to initialize an array before filling it with real data.

Syntax
np.zeros(shape)

shape → size of the array (rows, columns, etc.)

### Example

In [5]:
arr = np.zeros((2,3)) # it will create an array which contain 2 rows and 3 columns fill with all zeros
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


### 2️⃣np.ones()

np.ones() creates an array filled with ones (1).

Syntax

np.ones(shape)

### Example

In [6]:
arr = np.ones((3,3)) # it will create an array which contain 3 rows and 3 columns fill with all once
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3️⃣np.full()

np.full() creates an array filled with a specific value you choose.

Syntax

np.full(shape, value)

### Example

In [7]:
arr = np.full((3,3), 5) # it will create an array which contain 3 rows and 3 columns fill with those values which you enter
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


### 4️⃣ np.empty()

np.empty() creates an array without initializing values.

This means the array will contain random values already present in memory.

Syntax

np.empty(shape)

### Example

In [8]:
arr = np.empty((4,3))  # it will create an array which contain 4 rows and 3 columns fill with random or garbage values which are alredy present in memory
print(arr)

[[1.19041233e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.33664410e+160]
 [4.51328658e-090 6.38124964e-067 5.44890174e-067]
 [1.61872949e-051 3.99910963e+252 4.76075295e-038]]


## Numerical Ranges:

A numerical range is a set of numbers between a minimum and a maximum value.
It shows the limits within which numbers can exist.

### 1️⃣arange()

arange() is used to create an array with a sequence of numbers automatically.

In simple words:

It generates numbers in order within a given range.

#### Basic Syntax

np.arange(start, stop, step)

Where:

start → starting number

stop → ending number (not included)

step → difference between numbers

In [9]:
#Simple 
arr1 = np.arange(10) # it will create array from 0 to 9
print(arr1)

# From start to end

arr2 = np.arange(4,15)  # start from 4 and end with 14
print(arr2)

# From start to end with steps

arr3 = np.arange(4,20,3) # start from 4 and end with 19 with step of 3  (eg : 4,7,10,.....)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12 13 14]
[ 4  7 10 13 16 19]


### 2️⃣np.linspace()

np.linspace() creates an array of evenly spaced numbers between a start and stop value.

The important difference:

arange() → uses step size

linspace() → uses number of values

So with linspace() you decide how many numbers you want, not the step.

Syntax
np.linspace(start, stop, num)

Where:

start → starting value

stop → ending value

num → total numbers you want

⚠️ Unlike arange(), the stop value IS included.

### Example


In [10]:
arr = np.linspace(0,10,5) # it create an array of number you want (start from 0, end with 10, array contain 5 numbers) (both start and end include)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [11]:
# another example

arr = np.linspace(3,20,6) # it create an array of number you want (start from 3, end with 20, array contain 6 numbers) (both start and end include)
print(arr)

[ 3.   6.4  9.8 13.2 16.6 20. ]


## What is an Identity Matrix?

An identity matrix is a square matrix where:

All diagonal elements = 1

All other elements = 0

Example:

[[1 0 0]

 [0 1 0]

 [0 0 1]]

The 1s go from top-left to bottom-right (main diagonal).

Identity matrices are important in:

Linear Algebra

Machine Learning

Matrix multiplication

### 1️⃣np.identity()

np.identity() creates a square identity matrix.

Syntax

np.identity(n)

Where:

n = number of rows and columns

#### Example


In [12]:
arr = np.identity(3) # it create array which contain 3 rows and 3 columns and 1s on the main diagonal
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 2️⃣np.eye()

np.eye() also creates an identity-like matrix, but it is more flexible.

It can create non-square matrices.

Syntax

np.eye(rows, columns)

#### Example


In [13]:
arr = np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## Shape of an Array

The shape of a NumPy array tells us how many elements are in each dimension.

In simple words:

Shape tells the structure of the array (rows, columns, etc.).



In [14]:
# 0D array shape
arr0d_shape = np.array(20)
print(f"0D array : {arr0d_shape.shape}")

# 1D array shape
arr1d_shape = np.array([1,3,2,5])
print(f"1D array : {arr1d_shape.shape}")

# 2D array shape 
arr2d_shape = np.array([[1,2,3,4],
                        [8,5,7,6]])
print(f"2D array : {arr2d_shape.shape}")

# 3D array shape
arr3d_shape = np.array([[[1,2,3],
                        [4,5,6]],
                        [[9,8,7],
                         [8,7,6]]])
print(f"3D array : {arr3d_shape.shape}")

0D array : ()
1D array : (4,)
2D array : (2, 4)
3D array : (2, 2, 3)


## reshape()

reshape() is used to change the shape (structure) of an array without changing its data.

In simple words:

reshape() reorganizes the elements of an array into a new structure.

### Why We Use reshape()

Sometimes we have a 1D array, but we want to convert it into a 2D or 3D array.

Example:

[1 2 3 4 5 6]

We can reshape it into:

[[1 2 3]
 [4 5 6]]

Same numbers, different structure.

In [15]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


## Dimensions of an array

Tell about the dimension of an array (1D, 2D, 3D, etc)

### .ndim

.ndim tells the number of dimensions of an array.

#### Example


In [16]:
arr = np.array([[1,2,3],
               [4,5,6]])
print(arr.ndim)

2


## Size of array

Tell about the size of array that how many elements are present in an array

### .size

.size tells the total number of elements in the array.

#### Example

In [17]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.size)

6


### summary of .shape, .ndim, and .size:

In [18]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr.shape)
print(arr.ndim)
print(arr.size)

(3, 3)
2
9


## Memory & Types:
Memory and data types is important in NumPy because NumPy is designed to store data efficiently in memory, which is why it is fast for AI/ML.

### 1️⃣ .dtype

.dtype tells us the data type of elements stored in the array.

In NumPy, all elements in an array must have the same type.


### Example

In [19]:
arr = np.array([1.4, 2.3, 3.7, 4.2, 5.3])

print(arr.dtype)

float64


## 2️⃣ .itemsize

.itemsize tells how many bytes each element uses in memory.

1 byte = 8 bits

Meaning:

Each element uses 8 bytes of memory.

Example:

1 element → 8 bytes

### Example


In [20]:
arr = np.array([1,2,3,4])

print(arr.itemsize)

8


## 3️⃣ .nbytes

.nbytes tells the total memory used by the entire array.

Explanation:

4 elements × 8 bytes = 32 bytes

### Example

In [21]:
arr = np.array([1,2,3,4])

print(arr.nbytes)

32


## Type Casting

Sometimes we want to change the data type.

Example

In [22]:
arr = np.array([1,2,3,4])
new_arr = arr.astype(float)

print(new_arr)
print(new_arr.dtype)

[1. 2. 3. 4.]
float64
