# Array Manipulation & Reshaping

It means changing the structure, shape, or arrangement of an array.

For example, converting a 1D array into a 2D array or reorganizing its elements.

## Reshaping:

## 1️⃣ .reshape()

.reshape() is used to change the shape of an array without changing its data.

It only rearranges the elements into a new structure.

#### Important Rule

The total number of elements must remain the same.

### Example:

6 elements → can become (2×3) or (3×2)

But not (4×2) because that would need 8 elements.


### Example

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

new_arr = arr.reshape(3,2)

print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


## 2️⃣ .ravel()

.ravel() converts a multi-dimensional array into a 1D array.

It flattens the array.

### Example

In [2]:

arr = np.array([[1,2,3],
                [4,5,6]])

new_arr = arr.ravel()

print(new_arr)

[1 2 3 4 5 6]


## 3️⃣ .flatten()

.flatten() also converts an array into a 1D array.

Example

In [3]:
arr = np.array([[1,2,3],
                [4,5,6]])

new_arr = arr.flatten()

print(new_arr)

[1 2 3 4 5 6]


# Transpose
Transpose means converting rows into columns and columns into rows.

Example:

Original array

[[1 2 3]
 [4 5 6]]

After transpose

[[1 4]
 [2 5]
 [3 6]]

## 1️⃣ .T
.T is the simplest way to transpose an array.

### Example

In [4]:
arr = np.array([[1,3,4],
                [5,6,7]])
print(arr.T)

[[1 5]
 [3 6]
 [4 7]]


## 2️⃣np.transpose()
np.transpose() also transposes an array.

It does the same thing as .T, but it is written as a function.

### Example

In [5]:
arr = np.array([[2,8,6],
                [4,1,3],
                [6,6,2]])

new_arr = np.transpose(arr)
print(new_arr)

[[2 4 6]
 [8 1 6]
 [6 3 2]]


## 3️⃣ .swapaxes()

swapaxes() is used to swap two axes of an array.

This becomes useful when working with 3D or higher dimensional arrays.

### Example

In [6]:
arr = np.array([[1,2,3],
                [4,5,6]])

new_arr = np.swapaxes(arr,0,1)

print(new_arr)

[[1 4]
 [2 5]
 [3 6]]


# Adding/Removing Elements:
## 1) np.append()
np.append() is used to add one or more elements at the end of an array.

### Syntax
np.append(array, values)

### Example 1: Add One Element

In [7]:
arr = np.array([1,2,3,4,5])

new_arr = np.append(arr, 6)

new_arr

array([1, 2, 3, 4, 5, 6])

### Example 2: Add Multiple Elements

In [8]:
arr = np.array([1,2,3,4])

new_arr = np.append(arr, [5,6,7,8])

new_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

## 2) np.insert()
np.insert() is used to insert an element at a specific position (index).
### Syntax
np.insert(array, index, value)
### Example

In [9]:
arr = np.array([10,20,30,40])

new_arr = np.insert(arr, 3, 34)

new_arr

array([10, 20, 30, 34, 40])

## 3)np.delete()
np.delete() is used to remove an element from a specific position (index).
### Syntax
np.delete(array, index)
### Example

In [10]:
arr = np.array([10,20,30,40])

new_arr = np.delete(arr, 2)

new_arr

array([10, 20, 40])

# Joining & Splitting Arrays

## 1) np.concatenate():

np.concatenate() is used to join two or more arrays into a single array.

### Syntax:

np.concatenate((array1, array2))

### Example:

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.concatenate((arr1,arr2))

print(new_arr)

[1 2 3 4 5 6]


### Joining 2D array

In [17]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [4,2,7]])

new_arr = np.concatenate((arr1,arr2))

new_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 2, 7]])

## 2) np.vstack()

np.vstack() stands for Vertical Stack.

It joins arrays vertically (top to bottom).

### Syntax

np.vstack((array1, array2))

### Example

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.vstack((arr1,arr2))

new_arr

array([[1, 2, 3],
       [4, 5, 6]])

## 3) np.hstack()

np.hstack() stands for Horizontal Stack.

It joins arrays side by side.

### Syntax

np.hstack((array1, array2))

### Example

In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.hstack((arr1, arr2))

new_arr

array([1, 2, 3, 4, 5, 6])

### Example with 2D array

In [20]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [4,2,7]])

new_arr = np.hstack((arr1,arr2))

new_arr

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 4, 2, 7]])

## 4) np.split()

np.split() is used to divide one array into multiple smaller arrays.

### Syntax

np.split(array, number_of_parts)

### Example

In [21]:
arr = np.array([1,2,3,4,5,6])

new_arr = np.split(arr,3)

new_arr


[array([1, 2]), array([3, 4]), array([5, 6])]