# Indexing, Slicing & Filtering

## Basic Slicing
Slicing is used to select a range of elements from an array instead of selecting only one element.

### Syntax
array[start : stop : step]
##### Meaning
start → Index where slicing begins.

stop → Index where slicing ends (not included).

step → Number of positions to skip (optional).

Important: The stop index is not included in the result.

## slicing in 1D array

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

arr[1:4]

array([20, 30, 40])

### Slicing from the Beginning

If you omit the start, NumPy starts from index 0.

### Example

In [2]:
arr = ([10,20,30,40,50,60])

arr[:4]

[10, 20, 30, 40]

### Slicing to the End

If you omit the stop, NumPy continues until the last element.

### Example

In [3]:
arr = ([10,20,30,40,50,60])

arr[1:]

[20, 30, 40, 50, 60]

### Slicing with Step

The step tells NumPy how many positions to move each time.

### Example

In [4]:
arr = ([10,20,30,40,50,60])

arr[0:5:2]

[10, 30, 50]

### Slicing a 2D Array (Sub-matrix)

A sub-matrix is simply a smaller part of a 2D array.

### Example

In [5]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr[1:3,0:2]

array([[4, 5],
       [7, 8]])

## Integer Indexing (Selecting Specific Non-Sequential Elements)

Integer Indexing is used to select specific elements from an array by providing their index numbers.

In simple words:

Instead of selecting a continuous range (like slicing), you select exactly the elements you want.

### Why Do We Need It?

Suppose you have this array:

[10 20 30 40 50 60]

You only want:

10, 40, 60

These elements are not next to each other, so slicing cannot select them.

That's where Integer Indexing is used.

### Syntax
array[[index1, index2, index3]]

Notice the double square brackets:

arr[[0, 3, 5]]

Outer [] → Used for indexing.

Inner [] → Contains the list of index positions.

### Example(1D array):

In [6]:
arr = np.array([10,20,30,40,50,60])

arr[[0,3,5]]

array([10, 40, 60])

### Integer indexing in 2D array:

In [7]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr[[1,2]]

# selected rows

# row 1
# row 2

array([[4, 5, 6],
       [7, 8, 9]])

## Boolean indexing (Masking)

Boolean Indexing (also called Masking) is used to filter elements from an array based on a condition.

### How Boolean Indexing Works

It happens in two steps.

Step 1: Create a Boolean Mask

In [8]:
arr = np.array([2,4,6,8,10])

arr > 5

array([False, False,  True,  True,  True])

Step 2: Use the Mask

In [9]:
arr = np.array([2,4,6,8,10])

arr[arr > 5]

# NumPy keeps only the elements where the mask is True.

array([ 6,  8, 10])

### Example
Number less than 20

In [10]:
arr = np.array([10,20,30,40,50])

arr[arr < 20]

array([10])

### Another example
find even number in array

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

## Fancy Indexing
Fancy Indexing is a method of accessing multiple elements from an array using another array (or list) of index positions.

In simple words:

Instead of giving one index, you give a list or array of indices, and NumPy returns the corresponding elements.

### Why Do We Use Fancy Indexing?

Suppose we have this array:

[10 20 30 40 50 60]

You want to select:

20, 50, 60

These elements are not next to each other, so slicing cannot be used.

Fancy Indexing lets you select them easily.

### Syntax
array[[index1, index2, index3]]

or

array[np.array([index1, index2, index3])]
### Example: Using a List of Indices

In [12]:
arr = np.array([10,20,30,40,50,60])

arr[[2,3,5]]

array([30, 40, 60])

### Example: Using a NumPy Array of Indices

In [13]:
arr = np.array([100,200,300,400,500,600])

index = np.array([2,3,5])

arr[index]

# Here, index is itself a NumPy array.

array([300, 400, 600])

### Fancy Indexing in a 2D Array

In [14]:
arr = np.array([[10,20],
                [30,40],
                [50,60],
                [70,80]])

print(arr[[0,2]])

[[10 20]
 [50 60]]


### Selecting Specific Elements from a 2D Array

In [15]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])

print(arr[[0,2],[1,2]])

[20 90]


### Repeating Elements

In [16]:
arr = np.array([10,20,30])

print(arr[[0,0,2]])

[10 10 30]
