# Mathematical & Statistical Operations
## Arithmetic Operations in NumPy
### What is Element-wise Operation?
An element-wise operation means NumPy performs the operation between corresponding elements of two arrays.

For example:

Array 1: [10 20 30]

Array 2: [ 1  2  3]

10 + 1 = 11

20 + 2 = 22

30 + 3 = 33

Result:

[11 22 33]

So, NumPy works on the elements one by one.

## Element-wise Addition +
The + operator adds corresponding elements of two arrays.

In [1]:
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

result = arr1 + arr2

print(result)

[11 22 33]


## Element-wise Subtraction -
The - operator subtracts corresponding elements.

In [2]:
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

result = arr1 - arr2

print(result)

[ 9 18 27]


## Element-wise Multiplication *
The * operator multiplies corresponding elements.

In [3]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

result = arr1 * arr2

print(result)

[10 40 90]


## Element-wise Division /
The / operator divides corresponding elements.

In [4]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])

result = arr1 / arr2

print(result)

[5. 5. 6.]


## Broadcasting in NumPy
Broadcasting is a NumPy feature that allows us to perform arithmetic operations between arrays of different shapes.
### Simple Example

In [5]:
arr = np.array([10,20,30])

result = arr + 5

print(result)

[15 25 35]


## Broadcasting with two arrays

In [6]:
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

print(arr1 + arr2)


[11 22 33]


## Broadcasting with 2D array

In [7]:
arr = np.array([[10,20,30],
                [40,50,60]])

result = arr + 5

print(result)

# The single value 5 is broadcast across the entire array.

[[15 25 35]
 [45 55 65]]


## Broadcasting a 1D Array


In [ ]:
arr1 = np.array([[10,20,30],
                 [40,50,60]])

arr2 = np.array([1,2,3])

result = arr1 + arr2

print(result)


# NumPy applies: [1 2 3] to each row.

[[11 22 33]
 [41 52 63]]


### The Basic Broadcasting Rule
For NumPy to broadcast two arrays, their dimensions must be compatible.

The basic rule is:

Two dimensions are compatible when:

They are equal, or
One of them is 1.
For example:

(2, 3)
(3,)
These can work together.

But:

(2, 3)
(2,)
cannot be directly broadcast together for normal element-wise operations.

###  Why Does (2, 3) and (3,) Work?
Consider:

arr1.shape = (2, 3)
arr2.shape = (3,)
arr1 has:

2 rows
3 columns
arr2 has:

3 elements
NumPy matches the 3 with the 3 columns.

So it effectively applies arr2 to every row.

## Aggregates in NumPy
Aggregate functions are functions that take multiple values from an array and calculate a single summary value.

For example, if we have:

[10, 20, 30, 40, 50]

we can calculate:

Total → np.sum()

Average → np.mean()

Middle value → np.median()

Standard deviation → np.std()

Variance → np.var()

### np.sum()
np.sum() calculates the sum (total) of all elements in an array.
#### Example

In [9]:
arr = np.array([10,20,30,40,50])

result = np.sum(arr)

print(result)

150


### np.mean()
np.mean() calculates the average (mean) of the elements.

The formula is:

Mean = Sum of values / Number of values

#### Example

In [10]:
arr = np.array([10,20,30,40,50])

result = np.mean(arr)

print(result)

30.0


### np.median()
np.median() finds the middle value after the values are arranged in sorted order.

Example

In [13]:
arr = np.array([30,10,50,20,40,70,60])

result = np.median(arr)

print(result)

40.0


### np.std()
np.std() calculates the standard deviation.

Standard deviation tells us how spread out the values are from the mean.

Small standard deviation:

Values are close together.

Large standard deviation:

Values are more spread out.

#### Example


In [14]:
arr = np.array([10,20,30,40,50])

result = np.std(arr)

print(result)

14.142135623730951


### np.var()
np.var() calculates the variance of the values.

Variance is related to standard deviation.

The relationship is:

Variance = (Standard Deviation)²

#### Example

In [15]:
arr = np.array([10,20,30,40,50])

result = np.var(arr)

print(result)

200.0


## Min/Max Functions in NumPy
These functions are used to find the smallest value, largest value, and their positions in an array.
### np.min()
np.min() returns the smallest value in an array.
#### Example

In [ ]:
arr = np.array([10,5,30,15,25,20])

result = np.min(arr)

print(result)

5


### np.max()
np.max() returns the largest value in an array.

#### Example

In [17]:
arr = np.array([10,5,30,15,25,20])

result = np.max(arr)

print(result)

30


## np.argmin()
np.argmin() returns the index (position) of the smallest value.

It does not return the smallest value itself.

#### Example

In [18]:
arr = np.array([10,5,30,15,25,20])

result = np.argmin(arr)

print(result)

1


### np.argmax()
np.argmax() returns the index (position) of the largest value.

Again, it returns the position, not the value.

#### Example


In [19]:
arr = np.array([10,5,30,15,25,20])

result = np.argmax(arr)

print(result)

2


## Universal Functions (ufuncs) in NumPy
Universal Functions (ufuncs) are NumPy functions that perform a mathematical operation element by element on an array.

For example:

arr = [1, 4, 9]

If we use:

np.sqrt(arr)

NumPy calculates the square root of each element:

[1, 2, 3]

### np.sqrt()
np.sqrt() calculates the square root of each element.

#### Example

In [20]:
arr = np.array([1,4,9,16])

result = np.sqrt(arr)

print(result)

[1. 2. 3. 4.]


### np.exp()
np.exp() calculates e raised to the power of each element.

Here e is a mathematical constant approximately equal to:

e ≈ 2.71828

For example:

e² ≈ 7.389

Example

In [21]:
arr = np.array([0,1,2])

result = np.exp(arr)

print(result)

[1.         2.71828183 7.3890561 ]


### np.log()
np.log() calculates the natural logarithm (ln) of each element.

The natural logarithm uses base e.

#### Example:

In [22]:
arr = np.array([1,np.e,np.e**2])

result = np.log(arr)

print(result)

[0. 1. 2.]


### np.sin()
np.sin() calculates the sine of each element.

An important point:

NumPy's trigonometric functions use radians, not degrees.

#### Example

In [23]:
arr = np.array([0, np.pi/2, np.pi])

result = np.sin(arr)

print(result)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
