# Random Number Generation
Random number generation is very useful in AI/ML for things like initializing model parameters, creating test data, simulations, and sampling.
## np.random.rand()
np.random.rand() generates random numbers between 0 and 1 using a uniform distribution.

The values can include 0, but they are less than 1.

For example:

0.12, 0.75, 0.43, 0.91, ...

#### Example 1: Generate One Random Number

In [2]:
import numpy as np

number = np.random.rand()

print(number)

0.997740177013755


#### Example 2: Generate Multiple Random Numbers
You can give rand() a number telling it how many values you want.

In [8]:
numbers = np.random.rand(5)

print(numbers)

[0.79698578 0.28749176 0.90919368 0.55806056 0.63533472]


#### Example 3: Generate Random Numbers in Rows and Columns
You can provide multiple arguments.

In [10]:
numbers = np.random.rand(3,4)

print(numbers)

[[0.12483275 0.73093712 0.22400957 0.45251704]
 [0.72044415 0.40752749 0.93441687 0.90184234]
 [0.93307786 0.63291912 0.25654567 0.38560545]]


## np.random.randn()
np.random.randn() generates random numbers from a standard normal distribution.

The standard normal distribution has:

Mean = 0

Standard deviation = 1

The generated values are not restricted to 0 and 1.

For example, you might get:

-0.73, 0.21, 1.42, -1.15, 0.05

#### Example 1: Generate One Random Number

In [14]:
number = np.random.randn()

print(number)

2.077287821865689


#### Example 2: Generate Multiple Numbers


In [16]:
numbers = np.random.randn(5)

print(numbers)

[ 1.15643188 -0.72736849 -0.55473597  1.88553971  1.00073254]


#### Example 3: Generate a 2D Array

In [18]:
numbers = np.random.randn(2,3)

print(numbers)

[[-0.2692721   0.09115356  0.21811777]
 [-0.65890317  0.67485814 -0.98807575]]


## np.random.randint()
np.random.randint() is used to generate random integer numbers within a specified range.

In simple words:

np.random.randint() generates random whole numbers (integers).

For example:

2, 7, 15, 23

These are integers because they don't contain decimal values.

### Basic Syntax

np.random.randint(start, stop)

start → The starting value is included.

stop → The ending value is not included.
#### Example

In [21]:
number = np.random.randint(1,10)

print(number)

1


### Generate Multiple Random Integers
You can provide a third argument telling NumPy how many numbers you want.

#### Syntax
np.random.randint(start, stop, size)
#### Example

In [23]:
numbers = np.random.randint(1,10,5)

print(numbers)

[2 1 4 9 9]


### Generate a 2D Array of Random Integers
You can also specify the number of rows and columns.

In [24]:
numbers = np.random.randint(1,10,size=(2,3))

print(numbers)

[[6 2 3]
 [7 1 7]]


## Reproducibility — np.random.seed()
np.random.seed() is used to make random number generation reproducible.

In simple words:

A random seed allows you to get the same random numbers every time you run your code.

Normally, random functions generate different numbers each time.

#### For example:

In [3]:
np.random.seed(42)

numbers = np.random.randint(1,10,5)

print(numbers)

[7 4 8 5 7]


Now run the same code again. You will get the same numbers


### What Does 42 Mean?
In:

np.random.seed(42)

42 is called the seed value.

You can choose different seed values:

np.random.seed(10)

or:

np.random.seed(100)

or:

np.random.seed(123)

Different seeds generally produce different sequences.

The important thing is:

The same seed → the same sequence of random numbers.

## Distributions
## Normal Distribution
A normal distribution is a probability distribution where most values tend to be around the center (mean), while fewer values occur farther away from the center.

It is often represented by a bell-shaped curve.

For example, things such as:

Heights of people

Measurement errors

Exam scores (in some situations)

can sometimes be approximately normally distributed.

NumPy provides:

np.random.normal() 
 to generate random numbers following a normal distribution.

Basic syntax

np.random.normal(mean, standard_deviation, size)

Where:

mean → center of the distribution

standard_deviation → how spread out the values are

size → number of values to generate
#### Example

In [3]:
np.random.seed(42)

data = np.random.normal(50,10,5)

print(data)

[54.96714153 48.61735699 56.47688538 65.23029856 47.65846625]


## Binomial Distribution
The Binomial Distribution is used when we perform an experiment a fixed number of times, where each experiment has only two possible outcomes.

The two outcomes are often called:

Success or Failure

Simple example 
Imagine flipping a coin 10 times.

Each flip has two possible outcomes:

Heads → Success

Tails → Failure

We can use the binomial distribution to answer:

"How many times did we get Heads in 10 flips?"

NumPy provides:

np.random.binomial()

#### Basic syntax
np.random.binomial(n, p, size)

Where:

n → number of trials

p → probability of success in each trial

size → number of experiments/results to generate

#### Simple Example
Let's simulate 10 coin flips where the probability of getting Heads is 0.5.

In [6]:
np.random.seed(42)

result = np.random.binomial(10,0.5)

print(result)

4


### Generate Multiple Results
We can simulate the experiment many times.



In [7]:
np.random.seed(42)

result = np.random.binomial(10,0.5,5)

print(result)

[4 8 6 5 3]


#### Another Example
Suppose a student has a 70% chance of answering a question correctly.

We have 20 questions.

We can simulate this:

In [9]:
np.random.seed(42)

correct = np.random.binomial(20,0.7)

print(correct)


15


## Uniform Distribution
A Uniform Distribution is a probability distribution where every value in a given range has an equal chance of being selected.

In simple words:

Uniform distribution = values are selected evenly/randomly from a specified range.

For example, if we randomly select a number between 1 and 10, every number in that range has an equal chance of being selected.

NumPy provides:

np.random.uniform()

Basic syntax

np.random.uniform(low, high, size)

Where:

low → starting value

high → ending value

size → number of random values
#### Simple Example

In [12]:
np.random.seed(42)

number = np.random.uniform(1,10)

print(number)

4.370861069626263


### Generate Multiple Random Values


In [13]:
np.random.seed(42)

numbers = np.random.uniform(1,10,5)

print(numbers)

[4.37086107 9.55642876 7.58794548 6.38792636 2.40416776]
