# Linear Algebra
Linear algebra is very important in AI and Machine Learning because data, weights, features, and many mathematical operations are represented using vectors and matrices.

## np.dot()
np.dot() is used to calculate the dot product of arrays.

For two 1D arrays, it means:

Multiply corresponding elements and then add all the results.

### Simple Example


In [1]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.dot(arr1, arr2)

print(result)

32


### np.dot() With 2D Arrays
np.dot() can also perform matrix multiplication when working with 2D arrays.

### For example:



In [2]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

result = np.dot(A,B)

print(result)

[[19 22]
 [43 50]]


## @ Operator
The @ operator is used for matrix multiplication in Python and NumPy.

In simple words:

@ multiplies matrices according to the rules of matrix multiplication.

It is an alternative to using:

np.dot()

when working with 2D arrays.

### Simple Example
Let's start with two small matrices:



In [3]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

result = A @ B
print(result)

[[19 22]
 [43 50]]


## np.linalg.inv()
np.linalg.inv() is used to calculate the inverse of a square matrix.

In simple words:

The inverse of a matrix is a matrix that, when multiplied by the original matrix, produces the identity matrix.

It is similar to how:

5 × 1/5 = 1

For matrices:

A × A⁻¹ = I

where:

A → original matrix

A⁻¹ → inverse matrix

I → identity matrix

The syntax is:

np.linalg.inv(matrix)

linalg stands for linear algebra.

So:

np.linalg.inv()

means:

Find the inverse of a matrix using NumPy's linear algebra tools.

### Simple Example
Let's take this matrix:

In [11]:
A = np.array([[1,2],
              [3,4]])

inverse = np.linalg.inv(A)

print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


### Verify the Inverse
We can check whether the inverse is correct by multiplying the original matrix by its inverse.



In [13]:
result = A @ inverse

print(result)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [14]:
import numpy as np

A = np.array([[2, 1],
              [1, 1]])

inverse = np.linalg.inv(A)

print("Original matrix:")
print(A)

print("Inverse:")
print(inverse)

print("Verification:")
print(A @ inverse)

Original matrix:
[[2 1]
 [1 1]]
Inverse:
[[ 1. -1.]
 [-1.  2.]]
Verification:
[[1. 0.]
 [0. 1.]]


## np.linalg.det()
np.linalg.det() is used to calculate the determinant of a square matrix.

In simple words:

The determinant is a single number calculated from a square matrix.

The syntax is:

np.linalg.det(matrix)

Here:

np → NumPy

linalg → Linear Algebra

det() → Determinant

So:

np.linalg.det(A)

means:

Calculate the determinant of matrix A.

### Simple Example

In [15]:
A = np.array([[1,2],
              [3,4]])

determinant = np.linalg.det(A)

print(determinant)

-2.0000000000000004
