# Searching & Sorting
## np.sort()
np.sort() is used to sort the elements of an array.

By default, it sorts the values in ascending order, meaning:

Smallest → largest

For example:

[5, 2, 8, 1, 4]

becomes:

[1, 2, 4, 5, 8]
### Basic Syntax
np.sort(array)
#### Simple Example

In [1]:
import numpy as np

arr = np.array([5,2,8,1,4])

sorted_arr = np.sort(arr)

print(sorted_arr)

[1 2 4 5 8]


### Sorting in Descending Order
np.sort() directly sorts in ascending order.

If you want descending order, you can use slicing:



In [2]:
arr = np.array([5,2,8,1,4])

sorted_arr = np.sort(arr)

descending = sorted_arr[::-1]

print(descending)

[8 5 4 2 1]


### Sorting a 2D Array
np.sort() can also sort values inside a 2D array.



In [3]:
arr = np.array([[5,2,8],
                [1,7,3]])

result = np.sort(arr)

print(result)

[[2 5 8]
 [1 3 7]]


## np.argsort()
np.argsort() returns the indices (positions) that would arrange an array in sorted order.

In simple words:

np.sort() gives you the sorted values, while np.argsort() gives you the positions of those values.

### Simple Example

In [4]:
arr = np.array([30,10,20])

result = np.argsort(arr)

print(result)

[1 2 0]


### Using argsort() to Actually Sort the Array
The indices returned by argsort() can be used to access the original array.

In [6]:
arr = np.array([30,10,20])

indices = np.argsort(arr)

print(arr[indices])

[10 20 30]


## np.where()
np.where() is used to find the positions (indices) where a condition is true.

In simple words:

np.where() tells you where a condition is satisfied in an array.

### Basic Syntax
np.where(condition)

You give np.where() a condition, such as:

arr > 5

and it returns the indices where the condition is True.

#### Simple Example

In [8]:
arr = np.array([10,3,8,2,7])

result = np.where(arr > 5)

print(result)

(array([0, 2, 4]),)


### Finding a Specific Value
You can also use np.where() to find where a particular value occurs.

In [9]:
arr = np.array([10,20,30,20,40])

result = np.where(arr == 20)

print(result)

(array([1, 3]),)
