# Set operations
## np.unique()
np.unique() is used to find the unique values in an array.

In simple words:

np.unique() removes duplicate values and returns each value only once.
#### Simple Example


In [1]:
import numpy as np

arr = np.array([10,20,10,30,20,40])

result = np.unique(arr)

print(result)

[10 20 30 40]


## np.intersect1d()
np.intersect1d() is used to find the common values between two arrays.

In simple words:

np.intersect1d() finds the values that exist in both arrays.

Think of it as:

"Which values are present in both?"

### Basic Syntax
np.intersect1d(array1, array2)
It takes two arrays and returns their common unique values.

#### Simple Example

In [3]:
arr1 = np.array([1, 2, 3, 5, 4])
arr2 = np.array([3, 5, 4, 6, 7])

result = np.intersect1d(arr1,arr2)

print(result)

[3 4 5]


## np.union1d()
np.union1d() is used to find all unique values from two arrays combined.

In simple words:

np.union1d() combines two arrays and removes duplicate values.

Think of it as:

"Give me all the values that exist in either array, but only once."

### Basic Syntax
np.union1d(array1, array2)

It takes two arrays and returns their unique combined values.

### Simple Example

In [4]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

result = np.union1d(arr1, arr2)

print(result)

[1 2 3 4 5 6]
