# File Handling
## np.save()
np.save() is used to save a NumPy array to a file.

In simple words:

np.save() stores a NumPy array so you can use it again later without creating the array again.

NumPy normally saves the array in a file with the .npy extension.
### Basic Syntax
np.save(filename, array)

Where:

filename → name of the file you want to create

array → NumPy array you want to save
### Simple Example

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])

np.save("my_array.npy", arr)

### Saving a 2D Array
np.save() isn't limited to 1D arrays.

You can save a 2D array too:

In [2]:
arr = np.array([[1,2,3],
                [4,5,6]])

np.save("matrix.npy", arr)

## np.load()
np.load() is used to load a NumPy array from a file back into Python.

In simple words:

np.load() reads a saved NumPy array and brings it back into your program.

It is commonly used with the .npy files created by np.save().

### Basic Syntax
np.load(filename)

For example:

np.load("marks.npy")

This reads the marks.npy file and returns the NumPy array stored inside it.
#### Simple Example

In [3]:
marks = np.array([75, 82, 91, 68, 88])

np.save("marks.npy", marks)

### Load the Saved Array
Now we can load it:

In [4]:
loaded_marks = np.load("marks.npy")

print(loaded_marks)

[75 82 91 68 88]


## np.genfromtxt() for CSV Files
np.genfromtxt() is used to read data from a text file, especially CSV files, and convert it into a NumPy array.

In simple words:

np.genfromtxt() → reads data from a CSV file and converts it into a NumPy array.

CSV stands for Comma-Separated Values.

For example, a CSV file might contain:

Name,Age,Marks

Ali,20,85

Ahmed,21,90

Salman,20,88

2️⃣ Basic Syntax

np.genfromtxt("filename.csv", delimiter=",")
#### Important:

delimiter=","

tells NumPy:

"The values in this file are separated by commas."
#### Simple Example
Suppose you have a file called:

students.csv

containing:

10,20,30

40,50,60

70,80,90

You can read it using:




In [4]:
data = np.genfromtxt("student.csv", delimiter=",")

print(data)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
